version: "3.8"

volumes:
  datafiles:

services:
  db:
    image: mariadb:10.7.3
    volumes:
      - datafiles:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TCP_PORT: 3306

  webapp:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8888:80"
    #restart: always
    environment:
      - DBHOST=db
      - DBPORT=3306
      - DBPASSWORD=secret
      - DBNAME=bingo
      - DBUSER=root
      - ASPNETCORE_ENVIRONMENT=Development
